# Generated by Django 6.0.2 on 2026-02-18 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_video_video_file_profile_report_adminactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.video'),
        ),
    ]
